apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "quetzal.fullname" . }}-app-hpa
  labels:
    app.kubernetes.io/component: app
{{ include "quetzal.labels" . | indent 4}}
spec:
    minReplicas: 2
    maxReplicas: 10
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ include "quetzal.fullname" . }}-app
    targetCPUUtilizationPercentage: 75
