"""data api models

Revision ID: 0002
Revises: 0001
Create Date: 2019-01-28 14:22:08.091196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('_state', sa.Enum('INITIALIZING', 'READY', 'SCANNING', 'UPDATING', 'COMMITTING', 'DELETING', 'INVALID', 'CONFLICT', 'DELETED', name='workspacestate'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('temporary', sa.Boolean(), nullable=False),
    sa.Column('data_url', sa.String(length=2048), nullable=True),
    sa.Column('pg_schema_name', sa.String(length=63), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('fk_last_metadata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_last_metadata_id'], ['metadata.id'], name='workspace_fk_last_metadata_id', use_alter=True),
    sa.ForeignKeyConstraint(['fk_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'fk_user_id')
    )
    op.create_index('ix_workspace_name_user', 'workspace', ['name', 'fk_user_id'], unique=False)
    op.create_table('family',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fk_workspace_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('version IS NOT NULL OR fk_workspace_id IS NOT NULL', name='simul_null_check'),
    sa.ForeignKeyConstraint(['fk_workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'fk_workspace_id')
    )
    op.create_index(op.f('ix_family_name'), 'family', ['name'], unique=False)
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_file', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fk_family_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("json ? 'id'", name='check_id'),
    sa.ForeignKeyConstraint(['fk_family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_id_file'), 'metadata', ['id_file'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_id_file'), table_name='metadata')
    op.drop_table('metadata')
    op.drop_index(op.f('ix_family_name'), table_name='family')
    op.drop_table('family')
    op.drop_index('ix_workspace_name_user', table_name='workspace')
    op.drop_table('workspace')
    # ### end Alembic commands ###
