"""metadata model

Revision ID: 0003
Revises: 0002
Create Date: 2019-01-02 18:35:16.662672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_file', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fk_family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_id_file'), 'metadata', ['id_file'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metadata_id_file'), table_name='metadata')
    op.drop_table('metadata')
    # ### end Alembic commands ###
