## Default values for quetzal.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""


# Retained disk configuration (for database disk)
storage:
  type: pd-standard
  provisioner: kubernetes.io/gce-pd
  volumeBindingMode: Immediate

app:
  # general pod configuration
  image:
    repository: eu.gcr.io/quetzal-omind/dev/quetzal/app
    tag: 0.5.1
    pullPolicy: Always
  resources:
    limits:
      memory: 4Gi
      cpu: 1000m
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # app/worker specific configuration
  flask_env: production
  flaskSecretKey: +L!129XBD7VI_YJ+

  # Other configuration entries that should not be set here. They should be
  # set using --set key=value when doing helm install:
  # flask_secret_key: ...

worker:
  resources:
    limits:
      memory: 4Gi
      cpu: 1000m
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

#db:
#  image:
#    repository: eu.gcr.io/quetzal-omind/dev/quetzal/db
#    tag: 0.5.1
#    pullPolicy: Always
#  resources:
#    limits:
#      memory: 1Gi
#      cpu: 1000m
#    requests:
#      memory: 64Mi
#      cpu: 100m
#  nodeSelector: {}
#  tolerations: []
#  affinity: {}

  # Other configuration entries that should not be set here. They should be
  # set using --set key=value when doing helm install:
  # username: ...
  # password: ...

rabbitmq:
  image:
    repository: eu.gcr.io/quetzal-omind/dev/quetzal/rabbitmq
    tag: 0.5.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 256Mi
      cpu: 250m
    requests:
      memory: 128Mi
      cpu: 250m
  nodeSelector: {}
  tolerations: []
  affinity: {}
